# Generated by Django 5.0.7 on 2024-08-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uploadfilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='status',
            field=models.CharField(default='Encrypted', max_length=255, null=True),
        ),
    ]
