# Generated by Django 5.0.7 on 2024-08-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_uploadfilemodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static\\DecrptedFiles')),
                ('uploaderemail', models.EmailField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('file_name', models.CharField(max_length=255)),
                ('encrypted_data', models.BinaryField()),
                ('keyword', models.CharField(max_length=255)),
                ('privatekey', models.BinaryField()),
                ('Publickey', models.BinaryField()),
                ('status', models.CharField(default='pending', max_length=255)),
                ('key', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'RequestFileModel',
            },
        ),
    ]
