# Generated by Django 5.0.7 on 2024-08-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='static\\Files')),
                ('uploaderemail', models.EmailField(max_length=254)),
                ('file_name', models.CharField(max_length=255)),
                ('encrypted_data', models.BinaryField()),
                ('keyword', models.CharField(max_length=255)),
                ('privatekey', models.BinaryField()),
                ('Publickey', models.BinaryField()),
            ],
            options={
                'db_table': 'UploadFileModel',
            },
        ),
    ]
