# Generated by Django 6.0.3 on 2026-04-06 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0002_certificate_created_at_alter_certificate_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_hash',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vapp.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
