# Generated by Django 6.0.3 on 2026-04-07 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0004_alter_certificate_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vapp.user'),
        ),
    ]
